name: Build OpenWrt luci-app-zerotier Package

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    uses: ./.github/workflows/build_reusable.yml
    with:
      openwrt_branch: lede-17.01
